const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const packageJsonPath = path.join(rootDir, "package.json");
const outputPath = path.join(rootDir, "src", "version.ts");

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
const version = packageJson.version || "0.0.0";

const output = `// This file is auto-generated by scripts/generate-version.cjs.
// Do not edit manually.
export const SDK_VERSION = "${version}";
`;

fs.writeFileSync(outputPath, output, "utf8");
